version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: meditrack-db
    restart: always
    environment:
      POSTGRES_USER: meditrack_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: meditrack
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: meditrack-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@meditrack.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
