spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meditrack
    username: meditrack_user
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # Flyway owns schema changes
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration

  secrets:
    accounts-key: d04be89f7f6c4782baf7c95f60d337d7b9af5b8016ef3495c1e6f4a6c3c6b27d
